# Generated by Django 5.2 on 2025-06-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='receiver_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
